module.exports = [{ _id: 1, skill_title: "Visio"},
{ _id: 2, skill_title: "CSS 3"},
{ _id: 3, skill_title: "Bootstrap"},
{ _id: 4, skill_title: "WordPress"},
{ _id: 5, skill_title: "Ruby on Rails"},
{ _id: 6, skill_title: "Node JS"},
{ _id: 7, skill_title: "PHP"},
{ _id: 8, skill_title: "ReactJS"},
{ _id: 9, skill_title: "JQuery"},
{ _id: 10, skill_title: "Sass"},
{ _id: 11, skill_title: "ES6"},
{ _id: 12, skill_title: "Illustrator"},
{ _id: 13, skill_title: "QA & Testing"},
{ _id: 14, skill_title: "Photoshop"},
{ _id: 15, skill_title: "Responsive Design"},
{ _id: 16, skill_title: "Unity3D"},
{ _id: 17, skill_title: "AngularJS"},
{ _id: 18, skill_title: "MySQL"},
{ _id: 19, skill_title: "Illustrator"},
{ _id: 20, skill_title: "MongoDB"},
{ _id: 21, skill_title: "User Experience Design"},
{ _id: 22, skill_title: "Rhino"},
{ _id: 23, skill_title: "TypeScript"},
{ _id: 24, skill_title: "HTML5"},
{ _id: 25, skill_title: "Mobile Applications"},
{ _id: 26, skill_title: "User-centered Design"},
{ _id: 27, skill_title: "Cyber Defense"},
{ _id: 28, skill_title: "User Interface"},
{ _id: 29, skill_title: "InVision"},
{ _id: 30, skill_title: "Interaction Design"},
{ _id: 31, skill_title: "Social Media Marketing"},
{ _id: 32, skill_title: "SAP Implementation"},
{ _id: 33, skill_title: "Advertising"},
{ _id: 34, skill_title: "Python"},
{ _id: 35, skill_title: "Interactive Programming"},
{ _id: 36, skill_title: "OpenGL Shading Language (GLSL)"},
{ _id: 37, skill_title: "Real-time Graphics"},
{ _id: 38, skill_title: "Projection Mapping"},
{ _id: 39, skill_title: "After Effects"},
{ _id: 40, skill_title: "SCSS"},
{ _id: 41, skill_title: "AJAX"},
{ _id: 42, skill_title: "ExpressJS"},
{ _id: 43, skill_title: "Flux"},
{ _id: 44, skill_title: "Mean Stack"},
{ _id: 45, skill_title: "RequireJS"},
{ _id: 46, skill_title: "Firebase"},
{ _id: 47, skill_title: "End-to-end Testing"},
{ _id: 48, skill_title: "Jasmine Framework"},
{ _id: 49, skill_title: "Redux"},
{ _id: 50, skill_title: "Vue.js"}]
